# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b67ada2b837bbc6f2a0d974a00d469c92a5e2edc0984354fae97ca1cbb12726318f1543c384da696e234dcd3f3e79025ce29f051f509efc88b2d3239ee0517a6

test:
  secret_key_base: c2f968169fffb59cb202ecd016b5d740b788d18130ac763e29d4bc3d87f8e62fcd199fd238f5261070f0186a18a99a7e7e14bcd58998c382ec828a51d6e0f141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
